import '@repo/ui/styles.css'
import './globals.css'
import type { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans'
import { StoreProvider } from '../providers/store'

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <StoreProvider>
      <html lang='en' suppressHydrationWarning>
        <body className={GeistSans.className}>{children}</body>
      </html>
    </StoreProvider>
  )
}
